"use client";

import { useMemo, useState } from "react";
import Link from "next/link";

const fa = new Intl.NumberFormat("fa-IR");
const items = [
  {id:1,name:"گوشواره آویز لیانا",code:"RG-2401",type:"آویز",lock:"قلاب",use:"مجلسی",weight:4.4,price:54890000,wage:"دارد",img:"/liana-main.png",alt:"/liana-angle.png",badge:"فقط ۱ عدد"},
  {id:2,name:"گوشواره حلقه‌ای روژا",code:"RG-2402",type:"حلقه‌ای",lock:"کلیپسی",use:"روزمره",weight:3.2,price:40250000,wage:"دارد",img:"/liana-angle.png",alt:"/liana-macro.png",badge:"۲ عدد موجود"},
  {id:3,name:"گوشواره ظریف نور",code:"RG-2406",type:"میخی",lock:"پروانه‌ای",use:"روزمره",weight:2.4,price:30580000,wage:"دارد",img:"/liana-macro.png",alt:"/liana-stand.png",badge:"تازه رسیده"},
  {id:4,name:"گوشواره سبک باران",code:"RG-2374",type:"آویز",lock:"قلاب",use:"هدیه",weight:1.8,price:23400000,wage:"دارد",img:"/liana-stand.png",alt:"/liana-main.png",badge:"فقط ۱ عدد"},
  {id:5,name:"گوشواره طلای رستا",code:"RG-2410",type:"حلقه‌ای",lock:"کلیپسی",use:"روزمره",weight:2.9,price:36870000,wage:"دارد",img:"/collection-1.png",alt:"/collection-2.png",badge:"۳ عدد موجود"},
  {id:6,name:"گوشواره آویز مه‌دخت",code:"RG-2412",type:"آویز",lock:"اهرمی",use:"مجلسی",weight:5.1,price:63920000,wage:"دارد",img:"/collection-2.png",alt:"/collection-1.png",badge:"فقط ۱ عدد"},
];

export default function EarringsPage(){
  const [type,setType]=useState("همه"); const [sort,setSort]=useState("new"); const [maxWeight,setMaxWeight]=useState(6);
  const [compare,setCompare]=useState<number[]>([]); const [filtersOpen,setFiltersOpen]=useState(false); const [menu,setMenu]=useState(false);
  const shown=useMemo(()=>{let x=items.filter(i=>(type==="همه"||i.type===type)&&i.weight<=maxWeight); if(sort==="light")x=[...x].sort((a,b)=>a.weight-b.weight);if(sort==="price")x=[...x].sort((a,b)=>a.price-b.price);if(sort==="heavy")x=[...x].sort((a,b)=>b.weight-a.weight);return x},[type,sort,maxWeight]);
  const toggle=(id:number)=>setCompare(c=>c.includes(id)?c.filter(x=>x!==id):c.length<3?[...c,id]:c);
  return <main dir="rtl">
    <div className="notice"><span>ارسال امن و بیمه‌شده به سراسر ایران</span><span>پشتیبانی خرید: ۰۳۵۹۱۰۹۴۷۴۲</span></div>
    <header><div className="shell nav"><Link className="brand" href="/"><img src="/logo.png" alt="نشان طلای راضی"/><span><b>طلای راضی</b><small>درخشش، با خیال راحت</small></span></Link><nav className={menu?"links open":"links"}><Link href="/">صفحه اصلی</Link><Link className="active" href="/earrings">گوشواره‌ها</Link><a href="#products">دسته‌بندی محصولات</a><a href="#guide">راهنمای خرید</a><a href="#footer">تماس با ما</a></nav><div className="actions"><button aria-label="جستجو">⌕</button><button aria-label="حساب کاربری">♙</button><button aria-label="سبد خرید">⌑<i>۰</i></button><button className="menu" onClick={()=>setMenu(!menu)} aria-label="منو">☰</button></div></div></header>

    <section className="category-intro"><div className="shell"><div className="breadcrumb">خانه <span>←</span> محصولات <span>←</span> گوشواره</div><div className="category-title"><div><span className="eyebrow"><i/> مجموعه گوشواره‌های راضی</span><h1>گوشواره طلا</h1><p>مصنوعات نو و اجرت‌دار؛ از مدل‌های سبک روزمره تا آویزهای مجلسی، با نمایش شفاف وزن و قیمت نهایی.</p></div><div className="category-count"><b>{fa.format(items.length)}</b><span>مدل در این مجموعه<br/><small>تصاویر و قیمت‌ها در این پیش‌نمایش نمونه‌اند</small></span></div></div><div className="category-shortcuts">{[{t:"میخی",s:"ظریف و روزمره"},{t:"حلقه‌ای",s:"راحت و همیشگی"},{t:"آویز",s:"چشمگیر و مجلسی"}].map(x=><button className={type===x.t?"active":""} key={x.t} onClick={()=>setType(type===x.t?"همه":x.t)}><b>{x.t}</b><small>{x.s}</small><span>←</span></button>)}</div></div></section>

    <section className="catalog shell" id="products"><div className="catalog-top"><div><h2>انتخاب گوشواره</h2><p>{fa.format(shown.length)} محصول متناسب با انتخاب شما</p></div><button className="mobile-filter" onClick={()=>setFiltersOpen(true)}>☷ فیلتر محصولات</button><label>مرتب‌سازی <select value={sort} onChange={e=>setSort(e.target.value)}><option value="new">جدیدترین</option><option value="light">کمترین وزن</option><option value="heavy">بیشترین وزن</option><option value="price">کمترین قیمت</option></select></label></div>
      <div className="catalog-layout"><aside className={filtersOpen?"filter-panel open":"filter-panel"}><button className="filter-close" onClick={()=>setFiltersOpen(false)}>×</button><h3>فیلتر انتخاب</h3><div className="filter-block"><b>نوع گوشواره</b>{["همه","میخی","حلقه‌ای","آویز"].map(x=><label key={x}><input type="radio" name="type" checked={type===x} onChange={()=>setType(x)}/><span>{x}</span></label>)}</div><div className="filter-block"><b>حداکثر وزن</b><strong>تا {fa.format(maxWeight)} گرم</strong><input type="range" min="2" max="6" step=".5" value={maxWeight} onChange={e=>setMaxWeight(+e.target.value)}/><small><span>۲ گرم</span><span>۶ گرم</span></small></div><div className="filter-block muted-options"><b>نوع قفل</b><label><input type="checkbox"/> پروانه‌ای</label><label><input type="checkbox"/> قلاب</label><label><input type="checkbox"/> کلیپسی</label></div><div className="filter-block muted-options"><b>مناسب برای</b><label><input type="checkbox"/> استفاده روزمره</label><label><input type="checkbox"/> هدیه</label><label><input type="checkbox"/> استایل مجلسی</label></div><button className="reset" onClick={()=>{setType("همه");setMaxWeight(6)}}>پاک‌کردن فیلترها</button></aside>
      <div className="category-products">{shown.map(p=><article className="product-card" key={p.id}><div className="product-media"><img className="front" src={p.img} alt={p.name}/><img className="back" src={p.alt} alt={`نمای دوم ${p.name}`}/><span className="stock urgent">{p.badge}</span><button className="heart" aria-label="علاقه‌مندی">♡</button><span className="sample-photo">تصویر نمونه</span></div><div className="product-info"><div className="product-title"><div><h3>{p.name}</h3><small>کد {p.code}</small></div><b>{fa.format(p.weight)} <small>گرم</small></b></div><div className="mini-spec"><span>{p.type}</span><span>قفل {p.lock}</span><span>{p.use}</span><span>اجرت ساخت {p.wage}</span></div><div className="price"><span>قیمت نهایی نمونه · با احتساب اجرت</span><strong>{fa.format(p.price)} <small>تومان</small></strong></div><div className="card-actions"><button className="view">مشاهده محصول و جزئیات قیمت</button><label className={compare.includes(p.id)?"compare checked":"compare"}><input type="checkbox" checked={compare.includes(p.id)} onChange={()=>toggle(p.id)}/> مقایسه</label></div></div></article>)}</div></div>
      {shown.length===0&&<div className="empty"><b>مدلی با این وزن پیدا نشد</b><p>محدوده وزن را کمی افزایش دهید.</p><button onClick={()=>setMaxWeight(6)}>نمایش همه مدل‌ها</button></div>}
    </section>

    <section className="category-guide" id="guide"><div className="shell"><div><span className="eyebrow light"><i/> انتخاب مطمئن‌تر</span><h2>کدام گوشواره برای شما مناسب‌تر است؟</h2><p>برای استفاده طولانی، وزن و نوع قفل مهم‌تر از ظاهر اولیه‌اند. مدل‌های میخی و حلقه‌ای سبک برای روزمره و آویزها برای استایل رسمی انتخاب مناسب‌تری هستند.</p></div><div className="guide-points"><span><b>روزمره</b><small>سبک، قفل مطمئن، فرم ساده</small></span><span><b>هدیه</b><small>بسته‌بندی راضی و امکان مشاوره</small></span><span><b>مجلسی</b><small>آویز بلندتر و درخشش بیشتر</small></span></div></div></section>
    <section className="assurance shell"><h2>خرید با خیال راحت</h2><div><span>◇<b>ضمانت طلای ۱۸ عیار</b><small>اصالت و عیار تمام قطعات تضمین می‌شود.</small></span><span>▣<b>فاکتور رسمی و شفاف</b><small>وزن، اجرت ساخت و اجزای قانونی قیمت ثبت می‌شود.</small></span><span>⌁<b>ارسال امن و بیمه‌شده</b><small>بسته‌بندی مطمئن تا لحظه تحویل.</small></span><span>☏<b>مشاوره پیش از خرید</b><small>انتخاب مدل مناسب صورت و استایل.</small></span></div></section>
    <footer id="footer"><div className="shell footer-grid"><div className="footer-brand"><img src="/logo.png" alt="طلای راضی"/><h3>طلای راضی</h3><p>۴۵ سال تجربه، شفافیت و همراهی؛ از یزد برای سراسر ایران.</p></div><div><h4>فروشگاه</h4><a>گوشواره</a><a>گردنبند</a><a>انگشتر</a><a>دستبند و النگو</a></div><div><h4>راهنمای خرید</h4><a>انتخاب گوشواره</a><a>محاسبه قیمت</a><a>ارسال و تحویل</a><a>پیگیری سفارش</a></div><div><h4>ارتباط با ما</h4><a>یزد، صفائیه، مرکز خرید آریا</a><a>۰۳۵۹۱۰۹۴۷۴۲</a><a>@javaheri_razi</a></div></div><div className="shell copy"><span>© ۱۴۰۵ طلای راضی</span><span>پیش‌نمایش صفحه گروه گوشواره — اطلاعات نمونه‌اند</span></div></footer>
    {filtersOpen&&<div className="filter-shade" onClick={()=>setFiltersOpen(false)}/>} {compare.length>0&&<div className="compare-bar"><span><b>{fa.format(compare.length)}</b> گوشواره انتخاب شده</span><div>{compare.map(id=>{const p=items.find(x=>x.id===id)!;return <img key={id} src={p.img} alt={p.name}/>})}</div><button disabled={compare.length<2}>{compare.length<2?"یک مدل دیگر انتخاب کنید":"مقایسه مدل‌ها"}</button><button className="close" onClick={()=>setCompare([])}>×</button></div>}
  </main>
}
